### ISSUE TITLE
Cannot find module 

### ISSUE THREAD

**Issue by elmejor01** [jeanbmar/sc-compression#17]
I have been trying different versions of the script and it does not work for me, I have tried to move the path of the files and I still get the same problem. I did everything it says in the readme file. Thanks in advance.

![image](https://user-images.githubusercontent.com/30342849/206040301-32fd2581-cb1e-487e-8e1d-3cd366da9248.png)

**Comment by jeanbmar** [comment]
Hello,
File extension is mjs, you used msj!

**Comment by elmejor01** [comment]
I used npm install -g sc-compression and npm install sc-compression, then i copied the decompress.mjs, when i executed the node file i have this error. I put all the files in the path node_modules 
![image](https://user-images.githubusercontent.com/30342849/206128987-de808f8e-ee29-4459-af57-f980d008f507.png)

**Comment by jeanbmar** [comment]
The message means decompress.mjs is not there. Download the file, put it in your Desktop directory, go to desktop directory in cmd and run node decompress.mjs.
